# Environment variables on project-level:
# https://bitbucket.org/gfoidl/datacompression/admin/addon/admin/pipelines/repository-variables
# NAME   gfoidl.DataCompression

image:
    name: microsoft/dotnet:2.0.0-sdk

# Not good for BuildNumber
#clone:
#    depth: 1

pipelines:
    tags:
        v*:
            - step:
                script:
                    - chmod ugo+x ./build.sh
                    - export CI_BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                    - export TAG_NAME=$BITBUCKET_TAG
                    - ./build.sh

    default:
        - step:
            script:
                - chmod ugo+x ./build.sh
                - export CI_BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                - export BRANCH_NAME=$BITBUCKET_BRANCH
                - ./build.sh
